---
cloud:
  id: nightly-private-id
  key: nightly-private-key

cors:
  originEnds: localhost

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: CDK
  sapigType: core
  kustomizeFolder: dev

externalCert:
  projectId: example-project
  mtls:
    certPrefix: dev
    secretName: mtls-tls-cert
  sapig:
    certPrefix: dev
    secretName: sapig-tls-cert
  ttd:
    certPrefix: dev
    secretName: ttd-tls-cert

fidcConfigurator:
  enabled: true
  branch: HEAD
  repo: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer
  tag: latest

ig:
  tag: latest
  branch: HEAD
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: am-oauth2-ca-certs
  ob:
    signingkey:
      googleSecretName: ig-ob-signing-key

ingress:
  domain: localhost

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

testTrustedDirectory:
  tag: latest
  branch: HEAD

testUserAccountCreator:
  branch: HEAD
  deployment:
    type: Job
  repo: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer
  tag: latest